feat(ui): Skip empty elements.
superdispatch/ui pull request #170
Opened 2021-05-24 12:03 UTC by doniyor2109

2021-05-24 13:16 UTC, umidbekk commented
@doniyor2109 can you provide examples on storybook with the screenshots?

2021-05-24 13:23 UTC, umidbekk commented
and maybe it's better to hide empty elements completelty?

2021-05-25 05:10 UTC, doniyor2109 commented
> and maybe it's better to hide empty elements completelty?

Hmm. You mean by `display:none` ?

2021-05-25 05:42 UTC, umidbekk commented
> > and maybe it's better to hide empty elements completelty?
> 
> Hmm. You mean by `display:none` ?

yes

2021-05-25 05:44 UTC, umidbekk requested changes

2021-05-25 05:44 UTC, umidbekk commented on packages/ui/src/inline/Inline.stories.tsx
> +const Empty = () => null;
this will fail in Playroom example, you can add it to the `__docs__`

2021-05-25 07:13 UTC, doniyor2109 commented
> and maybe it's better to hide empty elements completely?

I have tried with `display: none` but there was some challenge with `&:first-child {padding-top: 0;}`. If empty element is first child then second element is adding extra padding (`first-child` rule not applying). 

Let me know if you have solution for this case.

2021-05-25 07:23 UTC, umidbekk commented
> > and maybe it's better to hide empty elements completely?
> 
> I have tried with `display: none` but there was some challenge with `&:first-child {padding-top: 0;}`. If empty element is first child then second element is adding extra padding (`first-child` rule not applying).
> 
> Let me know if you have solution for this case.

what about that?

```css
&:empty {
  display: none;
}

&:not(:empty):first-child {
  padding-top: 0;
}

```

2021-05-25 07:39 UTC, umidbekk commented
@doniyor2109 it didn't work, but I could achieve this with the `~` https://jsfiddle.net/2kbz51ty/20/

2021-05-25 07:46 UTC, umidbekk commented
@doniyor2109 updated: https://jsfiddle.net/2kbz51ty/31/

here is the css

```css
&:empty {
  display: none;
}
  
&:not(:empty) ~ & {
 padding-top: 15px;
}
```

How it works:
1. Hides all the empty elements
2. Finds non empty elements, and sets the padding for all the siblings that goes **after** the current element

2021-05-25 08:45 UTC, doniyor2109 commented
@umidbekk Still `Empty` is not found in playroom(
https://preview-170--ui-superdispatch.netlify.app/?path=/playroom/layout-inline--empty-elements

2021-05-25 12:04 UTC, umidbekk commented
@doniyor2109 oh, you also need to export it from the https://github.com/superdispatch/ui/blob/55c498d2ec82a08e0b82a9a70201937e380258db/scripts/generate-playroom-components.ts#L22

2021-05-26 04:55 UTC, merged